### PR TITLE
Project ready for review. Permission to merge to development

### PR DESCRIPTION
**Pull request by peterrobert**
1. Used firebase to store my information
2.Used single responsibility principal
3. Javascript classes implemented

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @peterrobert, 

Works great...really good job 
todo

Your code is also well organised

### Changes required 
- One can submit empty `todo` forms, you need to control this
todo2

- One can submit 'empty' `project` forms, you need to control this (with an error message sent to user)
todo3

- I can't also tell that you used `localStorage` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/localstorage_requirement.png)] because when I refresh the page, I loose every todo-list i typed.....please debug this too

### Let's polish this before we move on
Happy coding

Your code is well organised

**Comment by peterrobert** [comment]
Changes for the validation done as required. However, I did not use local storage. Instead, I used firebase to persist data. Kindly recheck on that. The data is been persisted

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required
The project has been well implemented.
There is a hard requirement that is preventing me from approving this project.

**REQUIRED**
* I can see that the data has been made persistent using firebase, but using the browser's local storage is a hard requirement as shown [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/localstorage_requirement.png).

**After making the changes, submit another request for review.**

**Happy Coding :computer:
Simon Wathigo.**

**Comment by peterrobert** [comment]
Implemented local storage as requested

**Review by whiz25 — APPROVED** [review]
## Approved :clap: 
You made all the required changes and it's a :+1: from me. Merge and proceed to the next milestone.

### Martin Afani

**Pull request merged**
